version: '3.2'
services:
  dev:
    build: 
      context: ..
      dockerfile: Dockerfile.dev
    volumes:
      - ..:/src:cached
    command: /bin/bash -c "dotnet build; while sleep 1000; do :; done"
    container_name: aquire_report_batch
    environment: 
      DB_SERVERNAME: report_rdb_primary
      DB_USERID: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: mysecretpassword
    depends_on:
      - rdb_primary
  rdb_primary:
    build:
      context: ../postgres
      dockerfile: Dockerfile.primary
    container_name: report_rdb_primary
    volumes:
      - primary_database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
  api:
    build: 
      context: ..
      dockerfile: Dockerfile.dev
    command: /bin/bash -c "dotnet run --project /src/Presentation/FinancialAnalysisAPI/FinancialAnalysisAPI.csproj"
    container_name: analysis_api
    environment:
      DB_SERVERNAME: report_rdb_readonly
      DB_USERID: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: mysecretpassword
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development
    expose:
      - 80
    ports:
      - "8080:80"
    depends_on:
      - rdb_readonly
  rdb_readonly:
    build:
      context: ../postgres
      dockerfile: Dockerfile.readonly
    command: postgres -c log_destination=stderr -c log_statement=all
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword
      PGPASSFILE: /.pgpass
    container_name: report_rdb_readonly
    volumes:
      - readonly_database:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      - rdb_primary
volumes:
  primary_database:
    driver: local
  readonly_database:
    driver: local