trigger:
- main
- release/*
- develop

pool:
  vmImage: 'ubuntu-20.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- template: buildAndTest.yml

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
  - template: pushImages.yml
    parameters:
      imageTag: 'stable'

- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}:
  - template: pushImages.yml
    parameters:
      imageTag: 'beta'

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
  - template: pushImages.yml
    parameters:
      imageTag: 'alpha'
