trigger:
- main
- release/*
- develop
- feature/*

pool:
  vmImage: 'ubuntu-20.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- template: buildAndTest.yml

- ${{ if eq(variables['Build.SourceBranch'], 'main') }}:
  - template: main.yml

- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}:
  - template: release.yml

- ${{ if eq(variables['Build.SourceBranch'], 'develop') }}:
  - template: develop.yml
