steps:
- task: Docker@2
  displayName: 'Login Dockerhub'
  inputs:
    containerRegistry: 'dockerRegistryServiceConnection'
    command: 'login'

- task: Docker@2
  displayName: 'Build and Push FinancialAnalysisAPI Image'
  inputs:
    containerRegistry: 'dockerRegistryServiceConnection'
    repository: 'harunari/financial_analysis_api'
    command: 'buildAndPush'
    Dockerfile: './Presentation/FinancialAnalysisAPI/Dockerfile'
    buildContext: '.'
    tags: |
      ${{ parameters.imageTag }}-$(Build.BuildId)
      ${{ parameters.imageTag }}

- task: Docker@2
  displayName: 'Build and Push AquireAccountItems Batch Image'
  inputs:
    containerRegistry: 'dockerRegistryServiceConnection'
    repository: 'harunari/aquire_account_items_batch'
    command: 'buildAndPush'
    Dockerfile: './Presentation/AquireAccountItems/Dockerfile'
    buildContext: '.'
    tags: |
      ${{ parameters.imageTag }}-$(Build.BuildId)
      ${{ parameters.imageTag }}

- task: Docker@2
  displayName: 'Build and Push AquireFinancialReports Batch Image'
  inputs:
    containerRegistry: 'dockerRegistryServiceConnection'
    repository: 'harunari/aquire_financial_reports_batch'
    command: 'buildAndPush'
    Dockerfile: './Presentation/AquireFinancialReports/Dockerfile'
    buildContext: '.'
    tags: |
      ${{ parameters.imageTag }}-$(Build.BuildId)
      ${{ parameters.imageTag }}

- task: Docker@2
  displayName: 'Build and Push ImportCorporationInfo Batch Image'
  inputs:
    containerRegistry: 'dockerRegistryServiceConnection'
    repository: 'harunari/import_corporation_info_batch'
    command: 'buildAndPush'
    Dockerfile: './Presentation/ImportCorporationInfo/Dockerfile'
    buildContext: '.'
    tags: |
      ${{ parameters.imageTag }}-$(Build.BuildId)
      ${{ parameters.imageTag }}

- task: Docker@2
  displayName: 'Build and Push Financial Report Primary Database Image'
  inputs:
    containerRegistry: 'dockerRegistryServiceConnection'
    repository: 'harunari/financial_report_primary_database'
    command: 'buildAndPush'
    Dockerfile: './postgres/Dockerfile.primary'
    buildContext: './postgres'
    tags: |
      ${{ parameters.imageTag }}-$(Build.BuildId)
      ${{ parameters.imageTag }}